// <auto-generated />
using System;
using BAI_1_5_EFCORE_CodeFirst.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BAI_1_5_EFCORE_CodeFirst.Migrations
{
    [DbContext(typeof(FpolyDBContext))]
    [Migration("20220727034754_CreateDB2707221045")]
    partial class CreateDB2707221045
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BAI_1_5_EFCORE_CodeFirst.DomainClass.Point", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSv")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MonHoc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdSv");

                    b.ToTable("Point");
                });

            modelBuilder.Entity("BAI_1_5_EFCORE_CodeFirst.DomainClass.SinhVien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Msv")
                        .HasMaxLength(200)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SinhVien");
                });

            modelBuilder.Entity("BAI_1_5_EFCORE_CodeFirst.DomainClass.Point", b =>
                {
                    b.HasOne("BAI_1_5_EFCORE_CodeFirst.DomainClass.SinhVien", "SinhVien")
                        .WithMany()
                        .HasForeignKey("IdSv");

                    b.Navigation("SinhVien");
                });
#pragma warning restore 612, 618
        }
    }
}
